[package]
name = "upi-adapter"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
acquirer-router = { path = "../../acquirer-router" }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
